services:
  portainer:
    container_name: portainer
    image: portainer/portainer:latest
    ports:
      - 9000:9000
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - data:/data

volumes:
  data:
    name: portainer_data
    driver: local